name: Build and test app in NCS docker container

on:
  pull_request:
  push:

jobs:
  set-image-tag:
    runs-on: ubuntu-22.04
    outputs:
      IMAGE_TAG: ${{ steps.set-output.outputs.IMAGE_TAG }}
    steps:
      - name: Compute or fetch container tag dynamically
        id: set-output
        run: echo "IMAGE_TAG=v2.7.99" >> $GITHUB_OUTPUT

  build-and-test-in-docker:
    runs-on: ubuntu-22.04
    needs: set-image-tag
    container: ghcr.io/nrfconnect/sdk-nrf-toolchain:${{ needs.set-image-tag.outputs.IMAGE_TAG }}
    defaults:
      run:
        # Bash shell is needed to set toolchain related environment variables in docker container
        # It is a workaround for GitHub Actions limitation https://github.com/actions/runner/issues/1964
        shell: bash
    steps:
      - name: Checkout repository with example application
        uses: actions/checkout@v4
        with:
          path: example-application

      - name: Prepare west project
        run: |
          west init -l example-application
          west update -o=--depth=1 -n

      - name: Build firmware
        working-directory: example-application
        run: |
          west twister -T app -v --inline-logs --integration

      - name: Store hex files
        uses: actions/upload-artifact@v4
        with:
          name: built-applications
          path: example-application/twister-out/**/zephyr/zephyr.hex

      - name: Twister Tests
        working-directory: example-application
        run: |
          west twister -T tests -v --inline-logs --integration
